### ISSUE TITLE
Question about comparison with Jin et al.'s work (CVPR2018)

### ISSUE THREAD

**Issue by zzh-tech** [rozumden/DeFMO#1]
Hi, thank you for your interesting work!
I have a question about the comparison of methods in your work.
When making comparisons, did you retrain Jin et al.'s model ("Learning to Extract a Video Sequence from a Single Motion-Blurred Image" from CVPR 2018), or did you just use their pre-trained checkpoints?
I couldn't find the training code on their [github page](https://github.com/MeiguangJin/Learning-to-Extract-a-Video-Sequence-from-a-Single-Motion-Blurred-Image).

**Comment by rozumden** [comment]
Hi, thanks for your question. We used their pre-trained models. One of the reasons is exactly what you mentioned: they don't provide the training code.

**Comment by zzh-tech** [comment]
Got it.
Thank you :)
