### ISSUE TITLE
Padding in Time-Consistency Loss

### ISSUE THREAD

**Issue by JLiu-Edinburgh** [rozumden/DeFMO#3]
Hi,

Congratulations!

I found that "padding = tuple(side // 10 for side in sh[:2]) + (0,)" for normalized cross-correlation. Does it only implement padding to the height axis, since the padding tuple will be of size (4//10, H//10, 0)?

Thanks a lot.

**Comment by rozumden** [comment]
Hi,

Thanks for spotting this bug! I apologize for it, it appeared after some code cleaning for the camera-ready code release. It is fixed now.

Actually, in our recent improved and speeded-up reimplementation (https://github.com/klaegera-eth/DeFMO), we have the correct padding: https://github.com/klaegera-eth/DeFMO/blob/master/defmo/training/modules/loss.py (line 401).

Best regards,
Denys
