### ISSUE TITLE
run on google colab!

### ISSUE THREAD

**Issue by bahmanjafari713** [rozumden/DeFMO#5]
I'm confused! and need to run the code on google colab or more explanation about how to implement that code in vscode or something else .if it  know someone please help me

**Comment by BhargavN02** [comment]
Can I know how to implement this code? While running run.py, the "OSError: No file or directory found at FMODetect.h5" error is displayed. A text file to run this would be helpful.

**Comment by rozumden** [comment]
Dear @BhargavN02 , I'm not sure how you got this error. This Github repository does not use FMODetect.

**Comment by rozumden** [comment]
Dear @ganikas , I suggest that you use it with Kornia: https://kornia.readthedocs.io/en/latest/feature.html

It's as simple as importing "from kornia.feature import DeFMO" .
